import Elemento from "./Elemento";
import "./Tabela.css";

const Tabela = () => {
  return (
    <div className="main-container">
      <div className="tabela-container">
        <div className="Grupo">
          <Elemento
            natomico="1"
            simbolo="H"
            nome="Hidrogênio"
            massa="1,008"
            tipo="hidrogenio"
          />
          <Elemento
            natomico="3"
            simbolo="Li"
            nome="Lítio"
            massa="6,94"
            tipo="metal-representativo"
          />
          <Elemento
            natomico="11"
            simbolo="Na"
            nome="Sódio"
            massa="22,99"
            tipo="metal-representativo"
          />
          <Elemento
            natomico="19"
            simbolo="K"
            nome="Potássio"
            massa="39,10"
            tipo="metal-representativo"
          />
          <Elemento
            natomico="37"
            simbolo="Rb"
            nome="Rubídio"
            massa="85,47"
            tipo="metal-representativo"
          />
          <Elemento
            natomico="55"
            simbolo="Cs"
            nome="Césio"
            massa="132,91"
            tipo="metal-representativo"
          />
          <Elemento
            natomico="87"
            simbolo="Fr"
            nome="Frâncio"
            massa="223,00"
            tipo="metal-representativo"
          />
        </div>
        <div className="Grupo">
          <Elemento
            natomico="4"
            simbolo="Be"
            nome="Berílio"
            massa="9,01"
            tipo="metal-representativo"
          />
          <Elemento
            natomico="12"
            simbolo="Mg"
            nome="Magnésio"
            massa="24,31"
            tipo="metal-representativo"
          />
          <Elemento
            natomico="20"
            simbolo="Ca"
            nome="Cálcio"
            massa="40,08"
            tipo="metal-representativo"
          />
          <Elemento
            natomico="38"
            simbolo="Sr"
            nome="Estrôncio"
            massa="87,62"
            tipo="metal-representativo"
          />
          <Elemento
            natomico="56"
            simbolo="Ba"
            nome="Bário"
            massa="137,33"
            tipo="metal-representativo"
          />
          <Elemento
            natomico="88"
            simbolo="Ra"
            nome="Rádio"
            massa="226,03"
            tipo="metal-representativo"
          />
        </div>
        <div className="Grupo">
          <Elemento
            natomico="21"
            simbolo="Sc"
            nome="Escândio"
            massa="44,96"
            tipo="metal-de-transicao-externa"
          />
          <Elemento
            natomico="39"
            simbolo="Y"
            nome="Ítrio"
            massa="88,91"
            tipo="metal-de-transicao-externa"
          />
          <Elemento
            natomico=" "
            simbolo="57-71"
            nome="Lantanídeos"
            massa=" "
            tipo="Lantanídeos"
          />
          <Elemento
            natomico=" "
            simbolo="89-103"
            nome="Actinídeos"
            massa=" "
            tipo="Actinídeos"
          />
        </div>
        <div className="Grupo">
          <Elemento
            natomico="22"
            simbolo="Ti"
            nome="Titânio"
            massa="47,87"
            tipo="metal-de-transicao-externa"
          />
          <Elemento
            natomico="40"
            simbolo="Zr"
            nome="Zircônio"
            massa="91,22"
            tipo="metal-de-transicao-externa"
          />
          <Elemento
            natomico="72"
            simbolo="Hf"
            nome="Háfnio"
            massa="178,49"
            tipo="metal-de-transicao-externa"
          />
          <Elemento
            natomico="104"
            simbolo="Rf"
            nome="Rutherfórdio"
            massa="267,00"
            tipo="metal-de-transicao-externa"
          />
        </div>
        <div className="Grupo">
          <Elemento
            natomico="23"
            simbolo="V"
            nome="Vanádio"
            massa="50,94"
            tipo="metal-de-transicao-externa"
          />
          <Elemento
            natomico="41"
            simbolo="Nb"
            nome="Nióbio"
            massa="92,91"
            tipo="metal-de-transicao-externa"
          />
          <Elemento
            natomico="73"
            simbolo="Ta"
            nome="Tantálio"
            massa="180,95"
            tipo="metal-de-transicao-externa"
          />
          <Elemento
            natomico="105"
            simbolo="Db"
            nome="Dúbnio"
            massa="270,00"
            tipo="metal-de-transicao-externa"
          />
        </div>
        <div className="Grupo">
          <Elemento
            natomico="24"
            simbolo="Cr"
            nome="Cromo"
            massa="52,00"
            tipo="metal-de-transicao-externa"
          />
          <Elemento
            natomico="42"
            simbolo="Mo"
            nome="Molibdênio"
            massa="95,94"
            tipo="metal-de-transicao-externa"
          />
          <Elemento
            natomico="74"
            simbolo="W"
            nome="Tungstênio"
            massa="183,84"
            tipo="metal-de-transicao-externa"
          />
          <Elemento
            natomico="106"
            simbolo="Sg"
            nome="Seabórgio"
            massa="271,00"
            tipo="metal-de-transicao-externa"
          />
        </div>
        <div className="Grupo">
          <Elemento
            natomico="25"
            simbolo="Mn"
            nome="Manganês"
            massa="54,938"
            tipo="metal-de-transicao-externa"
          />
          <Elemento
            natomico="43"
            simbolo="Tc"
            nome="Tecnécio"
            massa="98"
            tipo="metal-de-transicao-externa"
          />
          <Elemento
            natomico="75"
            simbolo="Re"
            nome="Rênio"
            massa="186,21"
            tipo="metal-de-transicao-externa"
          />
          <Elemento
            natomico="107"
            simbolo="Bh"
            nome="Bóhrio"
            massa="264"
            tipo="metal-de-transicao-externa"
          />
        </div>
        <div className="Grupo">
          <Elemento
            natomico="26"
            simbolo="Fe"
            nome="Ferro"
            massa="55,85"
            tipo="metal-de-transicao-externa"
          />
          <Elemento
            natomico="44"
            simbolo="Ru"
            nome="Rutênio"
            massa="101,1"
            tipo="metal-de-transicao-externa"
          />
          <Elemento
            natomico="76"
            simbolo="Os"
            nome="Ósmio"
            massa="190,23"
            tipo="metal-de-transicao-externa"
          />
          <Elemento
            natomico="108"
            simbolo="Hs"
            nome="Hássio"
            massa="270"
            tipo="metal-de-transicao-externa"
          />
        </div>
        <div className="Grupo">
          <Elemento
            natomico="27"
            simbolo="Co"
            nome="Cobalt"
            massa="58,933"
            tipo="metal-de-transicao-externa"
          />
          <Elemento
            natomico="45"
            simbolo="Rh"
            nome="Ródio"
            massa="102,91"
            tipo="metal-de-transicao-externa"
          />
          <Elemento
            natomico="77"
            simbolo="Ir"
            nome="Irídio"
            massa="192,22"
            tipo="metal-de-transicao-externa"
          />
          <Elemento
            natomico="109"
            simbolo="Mt"
            nome="Meitnério"
            massa="268"
            tipo="metal-de-transicao-externa"
          />
        </div>
        <div className="Grupo">
          <Elemento
            natomico="28"
            simbolo="Ni"
            nome="Níquel"
            massa="58,693"
            tipo="metal-de-transicao-externa"
          />
          <Elemento
            natomico="46"
            simbolo="Pd"
            nome="Paládio"
            massa="106,42"
            tipo="metal-de-transicao-externa"
          />
          <Elemento
            natomico="78"
            simbolo="Pt"
            nome="Platina"
            massa="195,08"
            tipo="metal-de-transicao-externa"
          />
          <Elemento
            natomico="110"
            simbolo="Ds"
            nome="Darmstádio"
            massa="271"
            tipo="metal-de-transicao-externa"
          />
        </div>
        <div className="Grupo">
          <Elemento
            natomico="29"
            simbolo="Cu"
            nome="Cobre"
            massa="63,546"
            tipo="metal-de-transicao-externa"
          />
          <Elemento
            natomico="47"
            simbolo="Ag"
            nome="Prata"
            massa="107,87"
            tipo="metal-de-transicao-externa"
          />
          <Elemento
            natomico="79"
            simbolo="Au"
            nome="Ouro"
            massa="196,97"
            tipo="metal-de-transicao-externa"
          />
          <Elemento
            natomico="111"
            simbolo="Rg"
            nome="Roentgênio"
            massa="272"
            tipo="metal-de-transicao-externa"
          />
        </div>
        <div className="Grupo">
          <Elemento
            natomico="30"
            simbolo="Zn"
            nome="Zinco"
            massa="65,39"
            tipo="metal-de-transicao-externa"
          />
          <Elemento
            natomico="48"
            simbolo="Cd"
            nome="Cádmio"
            massa="112,41"
            tipo="metal-de-transicao-externa"
          />
          <Elemento
            natomico="80"
            simbolo="Hg"
            nome="Mercúrio"
            massa="200,59"
            tipo="metal-de-transicao-externa"
          />
          <Elemento
            natomico="112"
            simbolo="Cn"
            nome="Copernício"
            massa="272"
            tipo="metal-de-transicao-externa"
          />
        </div>
        <div className="Grupo">
          <Elemento
            natomico="5"
            simbolo="B"
            nome="Boro"
            massa="10.81"
            tipo="nao-metais"
          />
          <Elemento
            natomico="13"
            simbolo="Al"
            nome="Aluminío"
            massa="26,982"
            tipo="metal-representativo"
          />
          <Elemento
            natomico="31"
            simbolo="Ga"
            nome="Gálio"
            massa="69,723"
            tipo="metal-representativo"
          />
          <Elemento
            natomico="49"
            simbolo="In"
            nome="Índio"
            massa="114,82"
            tipo="metal-representativo"
          />
          <Elemento
            natomico="81"
            simbolo="Tl"
            nome="Tálio"
            massa="204,38"
            tipo="metal-representativo"
          />
          <Elemento
            natomico="113"
            simbolo="Nh"
            nome="Nihômio"
            massa="286"
            tipo="metal-representativo"
          />
        </div>
        <div className="Grupo">
          <Elemento
            natomico="6"
            simbolo="C"
            nome="Carbono"
            massa="12,011"
            tipo="nao-metais"
          />
          <Elemento
            natomico="14"
            simbolo="Si"
            nome="Silício"
            massa="28,085"
            tipo="nao-metais"
          />
          <Elemento
            natomico="32"
            simbolo="Ge"
            nome="Germânio"
            massa="72,61"
            tipo="metal-representativo"
          />
          <Elemento
            natomico="50"
            simbolo="Sn"
            nome="Estanho"
            massa="118,71 "
            tipo="metal-representativo"
          />
          <Elemento
            natomico="82"
            simbolo="Pb"
            nome="Chumbo"
            massa="207,2"
            tipo="metal-representativo"
          />
          <Elemento
            natomico="114"
            simbolo="Fl"
            nome="Fleróvio"
            massa="286"
            tipo="metal-representativo"
          />
        </div>
        <div className="Grupo">
          <Elemento
            natomico="7"
            simbolo="N"
            nome="Nitrogênio"
            massa="14,007"
            tipo="nao-metais"
          />
          <Elemento
            natomico="15"
            simbolo="P"
            nome="Fósforo"
            massa="30,974"
            tipo="nao-metais"
          />
          <Elemento
            natomico="33"
            simbolo="As"
            nome="Arsênio"
            massa="74,922"
            tipo="nao-metais"
          />
          <Elemento
            natomico="51"
            simbolo="Sb"
            nome="Antimônio"
            massa="121,76"
            tipo="metal-representativo"
          />
          <Elemento
            natomico="83"
            simbolo="Bi"
            nome="Bísmuto"
            massa="208,98"
            tipo="metal-representativo"
          />
          <Elemento
            natomico="115"
            simbolo="Mc"
            nome="Moscóvio"
            massa="288"
            tipo="metal-representativo"
          />
        </div>
        <div className="Grupo">
          <Elemento
            natomico="8"
            simbolo="O"
            nome="Oxigênio"
            massa="15,999"
            tipo="nao-metais"
          />
          <Elemento
            natomico="16"
            simbolo="S"
            nome="Enxofre"
            massa="32,06"
            tipo="nao-metais"
          />
          <Elemento
            natomico="34"
            simbolo="Se"
            nome="Selênio"
            massa="78,96"
            tipo="nao-metais"
          />
          <Elemento
            natomico="52"
            simbolo="Te"
            nome="Telúrio"
            massa="127,60"
            tipo="nao-metais"
          />
          <Elemento
            natomico="84"
            simbolo="Po"
            nome="Polônio"
            massa="208,98"
            tipo="metal-representativo"
          />
          <Elemento
            natomico="116"
            simbolo="Lv"
            nome="Livermório"
            massa="293"
            tipo="metal-representativo"
          />
        </div>
        <div className="Grupo">
          <Elemento
            natomico="9"
            simbolo="F"
            nome="Flúor"
            massa="18,998"
            tipo="nao-metais"
          />
          <Elemento
            natomico="17"
            simbolo="Cl"
            nome="Cloro"
            massa="35,45"
            tipo="nao-metais"
          />
          <Elemento
            natomico="35"
            simbolo="Br"
            nome="Bromo"
            massa="79,904"
            tipo="nao-metais"
          />
          <Elemento
            natomico="53"
            simbolo="I"
            nome="Iodo"
            massa="126,90"
            tipo="nao-metais"
          />
          <Elemento
            natomico="85"
            simbolo="At"
            nome="Astato"
            massa="209,99"
            tipo="nao-metais"
          />
          <Elemento
            natomico="117"
            simbolo="Ts"
            nome="Tenessino"
            massa="294"
            tipo="nao-metais"
          />
        </div>
        <div className="Grupo">
          <Elemento
            natomico="2"
            simbolo="He"
            nome="Hélio"
            massa="4,0026"
            tipo="gases-nobres"
          />
          <Elemento
            natomico="10"
            simbolo="Ne"
            nome="Neônio"
            massa="20,180"
            tipo="gases-nobres"
          />
          <Elemento
            natomico="18"
            simbolo="Ar"
            nome="Argônio"
            massa="39,948"
            tipo="gases-nobres"
          />
          <Elemento
            natomico="36"
            simbolo="Kr"
            nome="Criptônio"
            massa="83,80"
            tipo="gases-nobres"
          />
          <Elemento
            natomico="54"
            simbolo="Xe"
            nome="Xenônio"
            massa="209,99"
            tipo="gases-nobres"
          />
          <Elemento
            natomico="86"
            simbolo="Rn"
            nome="Radônio"
            massa="294"
            tipo="gases-nobres"
          />
          <Elemento
            natomico="118"
            simbolo="Og"
            nome="Oganessônio"
            massa="294"
            tipo="gases-nobres"
          />
        </div>
      </div>
      <div className="Lantanídeos-Class">
      <Elemento
          natomico="57"
          simbolo="La"
          nome="Lantânio"
          massa="138,91"
          tipo="Lantanídeos"
        />
        <Elemento
          natomico="58"
          simbolo="Ce"
          nome="Cério"
          massa="140,116"
          tipo="Lantanídeos"
        />
        <Elemento
          natomico="59"
          simbolo="Pr"
          nome="Praseodímio"
          massa="140,90765"
          tipo="Lantanídeos"
        />
        <Elemento
          natomico="60"
          simbolo="Nd"
          nome="Neodímio"
          massa="144,242"
          tipo="Lantanídeos"
        />
        <Elemento
          natomico="61"
          simbolo="Pm"
          nome="Promécio"
          massa="144,91276"
          tipo="Lantanídeos"
        />
        <Elemento
          natomico="62"
          simbolo="Sm"
          nome="Samário"
          massa="150,36"
          tipo="Lantanídeos"
        />
        <Elemento
          natomico="63"
          simbolo="Eu"
          nome="Európio"
          massa="152,0"
          tipo="Lantanídeos"
        />
        <Elemento
          natomico="64"
          simbolo="Gd"
          nome="Gadolínio"
          massa="157,25"
          tipo="Lantanídeos"
        />
        <Elemento
          natomico="65"
          simbolo="Tb"
          nome="Térbio"
          massa="158,92535"
          tipo="Lantanídeos"
        />
        <Elemento
          natomico="66"
          simbolo="Dy"
          nome="Disprósio"
          massa="162,500"
          tipo="Lantanídeos"
        />
        <Elemento
          natomico="67"
          simbolo="Ho"
          nome="Hólmio"
          massa="164,93033"
          tipo="Lantanídeos"
        />
        <Elemento
          natomico="68"
          simbolo="Er"
          nome="Érbio"
          massa="167,259"
          tipo="Lantanídeos"
        />
        <Elemento
          natomico="69"
          simbolo="Tm"
          nome="Túlio"
          massa="168,93422"
          tipo="Lantanídeos"
        />
        <Elemento
          natomico="70"
          simbolo="Yb"
          nome="Itérbio"
          massa="173,045"
          tipo="Lantanídeos"
        />
        <Elemento
          natomico="71"
          simbolo="Lu"
          nome="Lutécio"
          massa="175,0"
          tipo="Lantanídeos"
        />
      </div>
      <div className="Actinídeos-Class">
      <Elemento
          natomico="89"
          simbolo="Ac"
          nome="Actínio"
          massa="227,03"
          tipo="Actinídeos"
        />
        <Elemento
          natomico="90"
          simbolo="Th"
          nome="Tório"
          massa="232,03805"
          tipo="Actinídeos"
        />
        <Elemento
          natomico="91"
          simbolo="Pa"
          nome="Protactínio"
          massa="231,03588"
          tipo="Actinídeos"
        />
        <Elemento
          natomico="92"
          simbolo="U"
          nome="Urânio"
          massa="238,02891"
          tipo="Actinídeos"
        />
        <Elemento
          natomico="93"
          simbolo="Np"
          nome="Netúnio"
          massa="237,04817"
          tipo="Actinídeos"
        />
        <Elemento
          natomico="94"
          simbolo="Pu"
          nome="Plutônio"
          massa="244,06420"
          tipo="Actinídeos"
        />
        <Elemento
          natomico="95"
          simbolo="Am"
          nome="Amerício"
          massa="243,06138"
          tipo="Actinídeos"
        />
        <Elemento
          natomico="96"
          simbolo="Cm"
          nome="Cúrio"
          massa="247,07035"
          tipo="Actinídeos"
        />
        <Elemento
          natomico="97"
          simbolo="Bk"
          nome="Berquélio"
          massa="247,07031"
          tipo="Actinídeos"
        />
        <Elemento
          natomico="98"
          simbolo="Cf"
          nome="Califórnio"
          massa="251,07959"
          tipo="Actinídeos"
        />
        <Elemento
          natomico="99"
          simbolo="Es"
          nome="Einstênio"
          massa="252,08298"
          tipo="Actinídeos"
        />
        <Elemento
          natomico="100"
          simbolo="Fm"
          nome="Férmio"
          massa="257,09511"
          tipo="Actinídeos"
        />
        <Elemento
          natomico="101"
          simbolo="Md"
          nome="Mendelévio"
          massa="258,09843"
          tipo="Actinídeos"
        />
        <Elemento
          natomico="102"
          simbolo="No"
          nome="Nobélio"
          massa="259,10100"
          tipo="Actinídeos"
        />
        <Elemento
          natomico="103"
          simbolo="Lr"
          nome="Laurêncio"
          massa="262,10969"
          tipo="Actinídeos"
        />
      </div>
    </div>
  );
};

export default Tabela;
